### PR TITLE
Use >= instead of == in requirements to avoid python dependency conflicts

### PR DESCRIPTION
**Pull request by vkuznet**

### CODE REVIEW

**Review by amaltaro — APPROVED** [review]
LGTM! Thanks Valentin.

**Comment by vkuznet** [comment]
@amaltaro should we merge it or use `~=`?

**Comment by amaltaro** [comment]
Oh, sorry Valentin. I thought it had the compatibility specifier (~=). I'd suggest to update it to `~=`. What do you think?

**Comment by vkuznet** [comment]
I update it to `~=` and squashed the changes. Please review again.

**Comment by amaltaro** [comment]
It looks good to me. I am also going to update this spec file in cmsdist to start using the same version for WMCore services.

**Review by amaltaro — APPROVED** [review]

**Pull request merged**
